# theme.toml for Bandstand theme

name = "bandstand"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/KeyofSamuel/bandstand-hugo-theme"
min_version = "0.152.0"

[author]
  name = "Samuel A. Campbell"
  homepage = "https://keyofsamuel.com"
